import os
import sys
import logging
from dotenv import load_dotenv

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_classic.chains.retrieval_qa.base import RetrievalQA

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI

# Set up logging configuration
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Load environment variables
load_dotenv()

# Verify that the GOOGLE_API_KEY is present
if not os.environ.get("GOOGLE_API_KEY"):
    logger.error("GOOGLE_API_KEY missing from environment.")
    raise ValueError("GOOGLE_API_KEY not found in environment variables. Please add it to your .env file.")

def load_and_split_pdf(pdf_path: str, chunk_size: int = 1000, chunk_overlap: int = 200):
    if not os.path.exists(pdf_path):
        logger.error(f"The file {pdf_path} does not exist.")
        raise FileNotFoundError(f"The file {pdf_path} does not exist.")
        
    logger.info(f"Loading document from {pdf_path}...")
    loader = PyPDFLoader(pdf_path)
    documents = loader.load()
    logger.info(f"Successfully Loaded {len(documents)} pages from the PDF.")
    
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        length_function=len
    )
    
    chunks = text_splitter.split_documents(documents)
    logger.info(f"Successfully split the text into {len(chunks)} chunks.")
    return chunks

def get_vector_store(chunks, persist_directory: str):
    logger.info("Initializing HuggingFace Embeddings...")
    # NOTE: We are using HuggingFace embeddings here. 
    # This is a free, local alternative to OpenAI or Google Embeddings.
    # It runs locally on your machine, requiring no API key and incurring zero cost. 
    embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
    
    logger.info(f"Generating embeddings and storing in Chroma DB at '{persist_directory}'...")
    db = Chroma.from_documents(
        documents=chunks,
        embedding=embeddings,
        persist_directory=persist_directory
    )
    
    logger.info("Successfully persisted the vector database locally!")
    return db

def build_qa_chain(vector_db):
    """
    Constructs the RetrievalQA chain combining a Google Gemini LLM and the Chroma Database.
    """
    logger.info("Initializing the ChatGoogleGenerativeAI LLM (Gemini)...")
    llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0)
    
    logger.info("Configuring the RetrievalQA Chain...")
    # Configure retriever for similarity search, returning top 3 results
    retriever = vector_db.as_retriever(
        search_type="similarity",
        search_kwargs={"k": 3}
    )
    
    # Initialize the QA Chain
    qa_chain = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff", # 'stuff' bundles retrieved chunks into the prompt context
        retriever=retriever,
        return_source_documents=True # Allows us to access what chunks were utilized
    )
    
    logger.info("Gemini + HuggingFace RAG Pipeline Built Successfully!")
    return qa_chain

def interactive_loop(qa_chain):
    """
    Accepts queries directly from terminal and executes the generative pipeline.
    """
    print("\n" + "="*55)
    print("🤖 Hybrid RAG Interactive Chat Loaded!")
    print("Type your questions below. Enter 'exit' or 'quit' to terminate.")
    print("="*55)
    
    while True:
        try:
            query = input("\n[?] Ask a question: ").strip()
            
            # Check for exit commands
            if query.lower() in ['exit', 'quit', 'q']:
                print("\nShutting down RAG system. Goodbye!")
                break
                
            if not query:
                continue
                
            logger.info("Processing query and generating response...")
            
            # Send context to the LLM via our initialized pipeline
            response = qa_chain.invoke({"query": query})
            
            # The answer key generated by RetrievalQA
            answer = response.get("result", "No answer generated.")
            source_docs = response.get("source_documents", [])
            
            # Formatted Output
            print("\n" + "-"*55)
            print(f"[*] ANSWER:\n{answer}")
            print("-"*55)
            print(f"(Context provided from {len(source_docs)} document chunks)\n")
            
        except KeyboardInterrupt:
            print("\nShutting down RAG system. Goodbye!")
            break
        except Exception as e:
            logger.error(f"Error during query execution: {e}")

def main():
    logger.info("Starting up Full Gemini/HF RAG application...")
    
    pdf_path = os.path.join("data", "sample.pdf")
    
    # Changed persist directory to avoid conflicts with previous Google/OpenAI embeddings
    persist_dir = "chroma_data_hf" 
    
    try:
        # Module 1: Load and Split Text
        chunks = load_and_split_pdf(pdf_path)
        
        # Module 2: Generate Vectors and Persist
        if chunks:
            vector_db = get_vector_store(chunks, persist_directory=persist_dir)
            
            # Module 3: Construct LLM pipeline
            qa_chain = build_qa_chain(vector_db)
            
            # Module 4: Run chat session from terminal
            interactive_loop(qa_chain)
            
    except Exception as e:
        logger.error(f"System initialization failed: {e}")

if __name__ == "__main__":
    main()
